---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-release
  namespace: {{ .Release.Namespace }}
data:
  chartName: {{ .Chart.Name | quote }}
  chartVersion: {{ .Chart.Version | quote }}
  releaseNamespace: {{ .Release.Namespace | quote }}
  releaseName: {{ .Release.Name | quote }}
